// automatically generated by the FlatBuffers compiler, do not modify

package edu.vanderbilt.chuilian.types;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class TypesChannelReport extends Table {
    public static TypesChannelReport getRootAsTypesChannelReport(ByteBuffer _bb) {
        return getRootAsTypesChannelReport(_bb, new TypesChannelReport());
    }

    public static TypesChannelReport getRootAsTypesChannelReport(ByteBuffer _bb, TypesChannelReport obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(int _i, ByteBuffer _bb) {
        bb_pos = _i;
        bb = _bb;
    }

    public TypesChannelReport __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public String topic() {
        int o = __offset(4);
        return o != 0 ? __string(o + bb_pos) : null;
    }

    public ByteBuffer topicAsByteBuffer() {
        return __vector_as_bytebuffer(4, 1);
    }

    public long numIOBytes() {
        int o = __offset(6);
        return o != 0 ? bb.getLong(o + bb_pos) : 0L;
    }

    public long numIOMsgs() {
        int o = __offset(8);
        return o != 0 ? bb.getLong(o + bb_pos) : 0L;
    }

    public long numPublications() {
        int o = __offset(10);
        return o != 0 ? bb.getLong(o + bb_pos) : 0L;
    }

    public long numSubscribers() {
        int o = __offset(12);
        return o != 0 ? bb.getLong(o + bb_pos) : 0L;
    }

    public static int createTypesChannelReport(FlatBufferBuilder builder,
                                               int topicOffset,
                                               long numIOBytes,
                                               long numIOMsgs,
                                               long numPublications,
                                               long numSubscribers) {
        builder.startObject(5);
        TypesChannelReport.addNumSubscribers(builder, numSubscribers);
        TypesChannelReport.addNumPublications(builder, numPublications);
        TypesChannelReport.addNumIOMsgs(builder, numIOMsgs);
        TypesChannelReport.addNumIOBytes(builder, numIOBytes);
        TypesChannelReport.addTopic(builder, topicOffset);
        return TypesChannelReport.endTypesChannelReport(builder);
    }

    public static void startTypesChannelReport(FlatBufferBuilder builder) {
        builder.startObject(5);
    }

    public static void addTopic(FlatBufferBuilder builder, int topicOffset) {
        builder.addOffset(0, topicOffset, 0);
    }

    public static void addNumIOBytes(FlatBufferBuilder builder, long numIOBytes) {
        builder.addLong(1, numIOBytes, 0L);
    }

    public static void addNumIOMsgs(FlatBufferBuilder builder, long numIOMsgs) {
        builder.addLong(2, numIOMsgs, 0L);
    }

    public static void addNumPublications(FlatBufferBuilder builder, long numPublications) {
        builder.addLong(3, numPublications, 0L);
    }

    public static void addNumSubscribers(FlatBufferBuilder builder, long numSubscribers) {
        builder.addLong(4, numSubscribers, 0L);
    }

    public static int endTypesChannelReport(FlatBufferBuilder builder) {
        int o = builder.endObject();
        return o;
    }
}

